global:
  scrape_interval: 10s

scrape_configs:
  - job_name: "superapp-gateway"
    static_configs:
      - targets: ["gateway:8000"]

  - job_name: "superapp-backend"
    static_configs:
      - targets: ["backend-us:9464", "backend-eu:9464", "backend-in:9464"]
