apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: aws-secrets-manager
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets-sa
            namespace: external-secrets
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: superapp-db-credentials
  namespace: superapp-prod
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: superapp-db-credentials # Name of the generated native K8s Secret
    creationPolicy: Owner
  data:
    - secretKey: url
      remoteRef:
        key: superapp/prod/database
        property: connection_string
    - secretKey: jwt_secret
      remoteRef:
        key: superapp/prod/auth
        property: jwt_secret_key
