"""add_encryption_fields

Revision ID: 2231003b3445
Revises: 576641b76b6e
Create Date: 2026-03-27 12:08:47.890253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2231003b3445'
down_revision: Union[str, Sequence[str], None] = '576641b76b6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_pii', sa.Column('passport_number', sa.String(), nullable=True))
    op.add_column('user_pii', sa.Column('encrypted_dek', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_pii', 'encrypted_dek')
    op.drop_column('user_pii', 'passport_number')
    # ### end Alembic commands ###
