"""add_suspicious_transactions

Revision ID: 576641b76b6e
Revises: 2fec4c3575be
Create Date: 2026-03-27 11:58:34.351094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '576641b76b6e'
down_revision: Union[str, Sequence[str], None] = '2fec4c3575be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suspicious_transactions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('transaction_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.transaction_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suspicious_transactions_transaction_id'), 'suspicious_transactions', ['transaction_id'], unique=False)
    op.create_index(op.f('ix_suspicious_transactions_user_id'), 'suspicious_transactions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_suspicious_transactions_user_id'), table_name='suspicious_transactions')
    op.drop_index(op.f('ix_suspicious_transactions_transaction_id'), table_name='suspicious_transactions')
    op.drop_table('suspicious_transactions')
    # ### end Alembic commands ###
