"""split_user_metadata_and_pii

Revision ID: 59ea10537868
Revises: a1b2c3d4e5f6
Create Date: 2026-03-27 11:52:50.915954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59ea10537868'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_pii',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('region', sa.Enum('UNSPECIFIED', 'INDIA', 'EU', 'US', name='region'), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('encrypted_pii', sa.String(), nullable=True),
    sa.Column('kyc_status', sa.Enum('UNSPECIFIED', 'PENDING', 'VERIFIED', 'FAILED', name='kycstatus'), nullable=True),
    sa.Column('last_modified_at', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_pii_email'), 'user_pii', ['email'], unique=False)
    op.create_index(op.f('ix_user_pii_phone_number'), 'user_pii', ['phone_number'], unique=False)
    op.create_index(op.f('ix_user_pii_user_id'), 'user_pii', ['user_id'], unique=False)
    op.add_column('users', sa.Column('email_hash', sa.String(), nullable=True))
    op.add_column('users', sa.Column('created_at', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('primary_region', sa.Enum('UNSPECIFIED', 'INDIA', 'EU', 'US', name='region'), nullable=True))
    op.add_column('users', sa.Column('account_status', sa.Enum('ACTIVE', 'SUSPENDED', 'DELETED', 'PENDING_VERIFICATION', name='accountstatus'), nullable=True))
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('did', sa.String(), nullable=True))
    op.add_column('users', sa.Column('did_document', sa.String(), nullable=True))
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.create_index(op.f('ix_users_did'), 'users', ['did'], unique=True)
    op.create_index(op.f('ix_users_email_hash'), 'users', ['email_hash'], unique=True)
    op.drop_column('users', 'password_hash')
    op.drop_column('users', 'name')
    op.drop_column('users', 'phone_number')
    op.drop_column('users', 'encrypted_pii')
    op.drop_column('users', 'email')
    op.drop_column('users', 'kyc_status')
    op.drop_column('users', 'region')
    op.drop_index(op.f('ix_webauthn_credentials_credential_id'), table_name='webauthn_credentials')
    op.create_index(op.f('ix_webauthn_credentials_credential_id'), 'webauthn_credentials', ['credential_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_webauthn_credentials_credential_id'), table_name='webauthn_credentials')
    op.create_index(op.f('ix_webauthn_credentials_credential_id'), 'webauthn_credentials', ['credential_id'], unique=False)
    op.add_column('users', sa.Column('region', sa.VARCHAR(length=11), nullable=True))
    op.add_column('users', sa.Column('kyc_status', sa.VARCHAR(length=11), nullable=True))
    op.add_column('users', sa.Column('email', sa.VARCHAR(), nullable=True))
    op.add_column('users', sa.Column('encrypted_pii', sa.VARCHAR(), nullable=True))
    op.add_column('users', sa.Column('phone_number', sa.VARCHAR(), nullable=True))
    op.add_column('users', sa.Column('name', sa.VARCHAR(), nullable=True))
    op.add_column('users', sa.Column('password_hash', sa.VARCHAR(), nullable=True))
    op.drop_index(op.f('ix_users_email_hash'), table_name='users')
    op.drop_index(op.f('ix_users_did'), table_name='users')
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=1)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=1)
    op.drop_column('users', 'did_document')
    op.drop_column('users', 'did')
    op.drop_column('users', 'is_admin')
    op.drop_column('users', 'account_status')
    op.drop_column('users', 'primary_region')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'email_hash')
    op.drop_index(op.f('ix_user_pii_user_id'), table_name='user_pii')
    op.drop_index(op.f('ix_user_pii_phone_number'), table_name='user_pii')
    op.drop_index(op.f('ix_user_pii_email'), table_name='user_pii')
    op.drop_table('user_pii')
    # ### end Alembic commands ###
