"""Initial migration

Revision ID: e220b45da808
Revises: 
Create Date: 2026-02-18 16:51:35.286155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e220b45da808'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('region', sa.Enum('UNSPECIFIED', 'INDIA', 'EU', 'US', name='region'), nullable=True),
    sa.Column('kyc_status', sa.Enum('UNSPECIFIED', 'PENDING', 'VERIFIED', 'FAILED', name='kycstatus'), nullable=True),
    sa.Column('encrypted_pii', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.create_table('wallets',
    sa.Column('wallet_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('currency', sa.Enum('UNSPECIFIED', 'USD', 'INR', 'EUR', name='currency'), nullable=True),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('wallet_id')
    )
    op.create_index(op.f('ix_wallets_wallet_id'), 'wallets', ['wallet_id'], unique=False)
    op.create_table('transactions',
    sa.Column('transaction_id', sa.String(), nullable=False),
    sa.Column('from_wallet_id', sa.String(), nullable=True),
    sa.Column('to_wallet_id', sa.String(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('timestamp', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['from_wallet_id'], ['wallets.wallet_id'], ),
    sa.ForeignKeyConstraint(['to_wallet_id'], ['wallets.wallet_id'], ),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    op.create_index(op.f('ix_transactions_transaction_id'), 'transactions', ['transaction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_transaction_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_wallets_wallet_id'), table_name='wallets')
    op.drop_table('wallets')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
