# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: policy.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'policy.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cpolicy.proto\x12\x06policy\"\x83\x01\n\x06Policy\x12\x11\n\tpolicy_id\x18\x01 \x01(\t\x12\x0e\n\x06region\x18\x02 \x01(\t\x12(\n\x05rules\x18\x03 \x03(\x0b\x32\x19.policy.Policy.RulesEntry\x1a,\n\nRulesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"P\n\x16\x43heckComplianceRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0e\n\x06\x61\x63tion\x18\x02 \x01(\t\x12\x15\n\rtarget_region\x18\x03 \x01(\t\":\n\x17\x43heckComplianceResponse\x12\x0f\n\x07\x61llowed\x18\x01 \x01(\x08\x12\x0e\n\x06reason\x18\x02 \x01(\t\"(\n\x16GetRegionPolicyRequest\x12\x0e\n\x06region\x18\x01 \x01(\t\"9\n\x17GetRegionPolicyResponse\x12\x1e\n\x06policy\x18\x01 \x01(\x0b\x32\x0e.policy.Policy2\xb7\x01\n\rPolicyService\x12R\n\x0f\x43heckCompliance\x12\x1e.policy.CheckComplianceRequest\x1a\x1f.policy.CheckComplianceResponse\x12R\n\x0fGetRegionPolicy\x12\x1e.policy.GetRegionPolicyRequest\x1a\x1f.policy.GetRegionPolicyResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'policy_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_POLICY_RULESENTRY']._loaded_options = None
  _globals['_POLICY_RULESENTRY']._serialized_options = b'8\001'
  _globals['_POLICY']._serialized_start=25
  _globals['_POLICY']._serialized_end=156
  _globals['_POLICY_RULESENTRY']._serialized_start=112
  _globals['_POLICY_RULESENTRY']._serialized_end=156
  _globals['_CHECKCOMPLIANCEREQUEST']._serialized_start=158
  _globals['_CHECKCOMPLIANCEREQUEST']._serialized_end=238
  _globals['_CHECKCOMPLIANCERESPONSE']._serialized_start=240
  _globals['_CHECKCOMPLIANCERESPONSE']._serialized_end=298
  _globals['_GETREGIONPOLICYREQUEST']._serialized_start=300
  _globals['_GETREGIONPOLICYREQUEST']._serialized_end=340
  _globals['_GETREGIONPOLICYRESPONSE']._serialized_start=342
  _globals['_GETREGIONPOLICYRESPONSE']._serialized_end=399
  _globals['_POLICYSERVICE']._serialized_start=402
  _globals['_POLICYSERVICE']._serialized_end=585
# @@protoc_insertion_point(module_scope)
