# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import policy_pb2 as policy__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in policy_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PolicyServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CheckCompliance = channel.unary_unary(
                '/policy.PolicyService/CheckCompliance',
                request_serializer=policy__pb2.CheckComplianceRequest.SerializeToString,
                response_deserializer=policy__pb2.CheckComplianceResponse.FromString,
                _registered_method=True)
        self.GetRegionPolicy = channel.unary_unary(
                '/policy.PolicyService/GetRegionPolicy',
                request_serializer=policy__pb2.GetRegionPolicyRequest.SerializeToString,
                response_deserializer=policy__pb2.GetRegionPolicyResponse.FromString,
                _registered_method=True)


class PolicyServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CheckCompliance(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRegionPolicy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PolicyServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CheckCompliance': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckCompliance,
                    request_deserializer=policy__pb2.CheckComplianceRequest.FromString,
                    response_serializer=policy__pb2.CheckComplianceResponse.SerializeToString,
            ),
            'GetRegionPolicy': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRegionPolicy,
                    request_deserializer=policy__pb2.GetRegionPolicyRequest.FromString,
                    response_serializer=policy__pb2.GetRegionPolicyResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'policy.PolicyService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('policy.PolicyService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PolicyService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CheckCompliance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/policy.PolicyService/CheckCompliance',
            policy__pb2.CheckComplianceRequest.SerializeToString,
            policy__pb2.CheckComplianceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRegionPolicy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/policy.PolicyService/GetRegionPolicy',
            policy__pb2.GetRegionPolicyRequest.SerializeToString,
            policy__pb2.GetRegionPolicyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
