# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: user.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'user.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nuser.proto\x12\x04user\"w\n\x04User\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x1c\n\x06region\x18\x04 \x01(\x0e\x32\x0c.user.Region\x12#\n\nkyc_status\x18\x05 \x01(\x0e\x32\x0f.user.KycStatus\"N\n\x11\x43reateUserRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x1c\n\x06region\x18\x03 \x01(\x0e\x32\x0c.user.Region\".\n\x12\x43reateUserResponse\x12\x18\n\x04user\x18\x01 \x01(\x0b\x32\n.user.User\"!\n\x0eGetUserRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"+\n\x0fGetUserResponse\x12\x18\n\x04user\x18\x01 \x01(\x0b\x32\n.user.User\"5\n\x14UpdateProfileRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\"1\n\x15UpdateProfileResponse\x12\x18\n\x04user\x18\x01 \x01(\x0b\x32\n.user.User*P\n\x06Region\x12\x16\n\x12REGION_UNSPECIFIED\x10\x00\x12\x10\n\x0cREGION_INDIA\x10\x01\x12\r\n\tREGION_EU\x10\x02\x12\r\n\tREGION_US\x10\x03*o\n\tKycStatus\x12\x1a\n\x16KYC_STATUS_UNSPECIFIED\x10\x00\x12\x16\n\x12KYC_STATUS_PENDING\x10\x01\x12\x17\n\x13KYC_STATUS_VERIFIED\x10\x02\x12\x15\n\x11KYC_STATUS_FAILED\x10\x03\x32\xd0\x01\n\x0bUserService\x12?\n\nCreateUser\x12\x17.user.CreateUserRequest\x1a\x18.user.CreateUserResponse\x12\x36\n\x07GetUser\x12\x14.user.GetUserRequest\x1a\x15.user.GetUserResponse\x12H\n\rUpdateProfile\x12\x1a.user.UpdateProfileRequest\x1a\x1b.user.UpdateProfileResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REGION']._serialized_start=455
  _globals['_REGION']._serialized_end=535
  _globals['_KYCSTATUS']._serialized_start=537
  _globals['_KYCSTATUS']._serialized_end=648
  _globals['_USER']._serialized_start=20
  _globals['_USER']._serialized_end=139
  _globals['_CREATEUSERREQUEST']._serialized_start=141
  _globals['_CREATEUSERREQUEST']._serialized_end=219
  _globals['_CREATEUSERRESPONSE']._serialized_start=221
  _globals['_CREATEUSERRESPONSE']._serialized_end=267
  _globals['_GETUSERREQUEST']._serialized_start=269
  _globals['_GETUSERREQUEST']._serialized_end=302
  _globals['_GETUSERRESPONSE']._serialized_start=304
  _globals['_GETUSERRESPONSE']._serialized_end=347
  _globals['_UPDATEPROFILEREQUEST']._serialized_start=349
  _globals['_UPDATEPROFILEREQUEST']._serialized_end=402
  _globals['_UPDATEPROFILERESPONSE']._serialized_start=404
  _globals['_UPDATEPROFILERESPONSE']._serialized_end=453
  _globals['_USERSERVICE']._serialized_start=651
  _globals['_USERSERVICE']._serialized_end=859
# @@protoc_insertion_point(module_scope)
