# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: wallet.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'wallet.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cwallet.proto\x12\x06wallet\"a\n\x06Wallet\x12\x11\n\twallet_id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\"\n\x08\x63urrency\x18\x03 \x01(\x0e\x32\x10.wallet.Currency\x12\x0f\n\x07\x62\x61lance\x18\x04 \x01(\x01\"J\n\x13\x43reateWalletRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\"\n\x08\x63urrency\x18\x02 \x01(\x0e\x32\x10.wallet.Currency\"6\n\x14\x43reateWalletResponse\x12\x1e\n\x06wallet\x18\x01 \x01(\x0b\x32\x0e.wallet.Wallet\"&\n\x11GetBalanceRequest\x12\x11\n\twallet_id\x18\x01 \x01(\t\"4\n\x12GetBalanceResponse\x12\x1e\n\x06wallet\x18\x01 \x01(\x0b\x32\x0e.wallet.Wallet\"T\n\x14TransferFundsRequest\x12\x16\n\x0e\x66rom_wallet_id\x18\x01 \x01(\t\x12\x14\n\x0cto_wallet_id\x18\x02 \x01(\t\x12\x0e\n\x06\x61mount\x18\x03 \x01(\x01\"Q\n\x15TransferFundsResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x16\n\x0etransaction_id\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t*Z\n\x08\x43urrency\x12\x18\n\x14\x43URRENCY_UNSPECIFIED\x10\x00\x12\x10\n\x0c\x43URRENCY_USD\x10\x01\x12\x10\n\x0c\x43URRENCY_INR\x10\x02\x12\x10\n\x0c\x43URRENCY_EUR\x10\x03\x32\xed\x01\n\rWalletService\x12I\n\x0c\x43reateWallet\x12\x1b.wallet.CreateWalletRequest\x1a\x1c.wallet.CreateWalletResponse\x12\x43\n\nGetBalance\x12\x19.wallet.GetBalanceRequest\x1a\x1a.wallet.GetBalanceResponse\x12L\n\rTransferFunds\x12\x1c.wallet.TransferFundsRequest\x1a\x1d.wallet.TransferFundsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'wallet_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CURRENCY']._serialized_start=518
  _globals['_CURRENCY']._serialized_end=608
  _globals['_WALLET']._serialized_start=24
  _globals['_WALLET']._serialized_end=121
  _globals['_CREATEWALLETREQUEST']._serialized_start=123
  _globals['_CREATEWALLETREQUEST']._serialized_end=197
  _globals['_CREATEWALLETRESPONSE']._serialized_start=199
  _globals['_CREATEWALLETRESPONSE']._serialized_end=253
  _globals['_GETBALANCEREQUEST']._serialized_start=255
  _globals['_GETBALANCEREQUEST']._serialized_end=293
  _globals['_GETBALANCERESPONSE']._serialized_start=295
  _globals['_GETBALANCERESPONSE']._serialized_end=347
  _globals['_TRANSFERFUNDSREQUEST']._serialized_start=349
  _globals['_TRANSFERFUNDSREQUEST']._serialized_end=433
  _globals['_TRANSFERFUNDSRESPONSE']._serialized_start=435
  _globals['_TRANSFERFUNDSRESPONSE']._serialized_end=516
  _globals['_WALLETSERVICE']._serialized_start=611
  _globals['_WALLETSERVICE']._serialized_end=848
# @@protoc_insertion_point(module_scope)
