# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from protos import kyc_pb2 as protos_dot_kyc__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in protos/kyc_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class KycServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.InitiateKyc = channel.unary_unary(
                '/kyc.KycService/InitiateKyc',
                request_serializer=protos_dot_kyc__pb2.InitiateKycRequest.SerializeToString,
                response_deserializer=protos_dot_kyc__pb2.InitiateKycResponse.FromString,
                _registered_method=True)
        self.GetKycStatus = channel.unary_unary(
                '/kyc.KycService/GetKycStatus',
                request_serializer=protos_dot_kyc__pb2.GetKycStatusRequest.SerializeToString,
                response_deserializer=protos_dot_kyc__pb2.GetKycStatusResponse.FromString,
                _registered_method=True)
        self.UpdateKycStatus = channel.unary_unary(
                '/kyc.KycService/UpdateKycStatus',
                request_serializer=protos_dot_kyc__pb2.UpdateKycStatusRequest.SerializeToString,
                response_deserializer=protos_dot_kyc__pb2.UpdateKycStatusResponse.FromString,
                _registered_method=True)


class KycServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def InitiateKyc(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetKycStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateKycStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_KycServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'InitiateKyc': grpc.unary_unary_rpc_method_handler(
                    servicer.InitiateKyc,
                    request_deserializer=protos_dot_kyc__pb2.InitiateKycRequest.FromString,
                    response_serializer=protos_dot_kyc__pb2.InitiateKycResponse.SerializeToString,
            ),
            'GetKycStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetKycStatus,
                    request_deserializer=protos_dot_kyc__pb2.GetKycStatusRequest.FromString,
                    response_serializer=protos_dot_kyc__pb2.GetKycStatusResponse.SerializeToString,
            ),
            'UpdateKycStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateKycStatus,
                    request_deserializer=protos_dot_kyc__pb2.UpdateKycStatusRequest.FromString,
                    response_serializer=protos_dot_kyc__pb2.UpdateKycStatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kyc.KycService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('kyc.KycService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class KycService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def InitiateKyc(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kyc.KycService/InitiateKyc',
            protos_dot_kyc__pb2.InitiateKycRequest.SerializeToString,
            protos_dot_kyc__pb2.InitiateKycResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetKycStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kyc.KycService/GetKycStatus',
            protos_dot_kyc__pb2.GetKycStatusRequest.SerializeToString,
            protos_dot_kyc__pb2.GetKycStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateKycStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kyc.KycService/UpdateKycStatus',
            protos_dot_kyc__pb2.UpdateKycStatusRequest.SerializeToString,
            protos_dot_kyc__pb2.UpdateKycStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
