# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/kyc.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'protos/kyc.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protos import user_pb2 as protos_dot_user__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10protos/kyc.proto\x12\x03kyc\x1a\x11protos/user.proto\"\x86\x01\n\x12InitiateKycRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x1c\n\x06region\x18\x02 \x01(\x0e\x32\x0c.user.Region\x12\x15\n\rdocument_type\x18\x03 \x01(\t\x12\x13\n\x0b\x64ocument_id\x18\x04 \x01(\t\x12\x15\n\rencoded_image\x18\x05 \x01(\t\"W\n\x13InitiateKycResponse\x12\x0e\n\x06kyc_id\x18\x01 \x01(\t\x12\x1f\n\x06status\x18\x02 \x01(\x0e\x32\x0f.user.KycStatus\x12\x0f\n\x07message\x18\x03 \x01(\t\"&\n\x13GetKycStatusRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"H\n\x14GetKycStatusResponse\x12\x1f\n\x06status\x18\x01 \x01(\x0e\x32\x0f.user.KycStatus\x12\x0f\n\x07message\x18\x02 \x01(\t\"[\n\x16UpdateKycStatusRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x1f\n\x06status\x18\x02 \x01(\x0e\x32\x0f.user.KycStatus\x12\x0f\n\x07message\x18\x03 \x01(\t\"*\n\x17UpdateKycStatusResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\xe1\x01\n\nKycService\x12@\n\x0bInitiateKyc\x12\x17.kyc.InitiateKycRequest\x1a\x18.kyc.InitiateKycResponse\x12\x43\n\x0cGetKycStatus\x12\x18.kyc.GetKycStatusRequest\x1a\x19.kyc.GetKycStatusResponse\x12L\n\x0fUpdateKycStatus\x12\x1b.kyc.UpdateKycStatusRequest\x1a\x1c.kyc.UpdateKycStatusResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.kyc_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INITIATEKYCREQUEST']._serialized_start=45
  _globals['_INITIATEKYCREQUEST']._serialized_end=179
  _globals['_INITIATEKYCRESPONSE']._serialized_start=181
  _globals['_INITIATEKYCRESPONSE']._serialized_end=268
  _globals['_GETKYCSTATUSREQUEST']._serialized_start=270
  _globals['_GETKYCSTATUSREQUEST']._serialized_end=308
  _globals['_GETKYCSTATUSRESPONSE']._serialized_start=310
  _globals['_GETKYCSTATUSRESPONSE']._serialized_end=382
  _globals['_UPDATEKYCSTATUSREQUEST']._serialized_start=384
  _globals['_UPDATEKYCSTATUSREQUEST']._serialized_end=475
  _globals['_UPDATEKYCSTATUSRESPONSE']._serialized_start=477
  _globals['_UPDATEKYCSTATUSRESPONSE']._serialized_end=519
  _globals['_KYCSERVICE']._serialized_start=522
  _globals['_KYCSERVICE']._serialized_end=747
# @@protoc_insertion_point(module_scope)
