# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from protos import wallet_pb2 as protos_dot_wallet__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in protos/wallet_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class WalletServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateWallet = channel.unary_unary(
                '/wallet.WalletService/CreateWallet',
                request_serializer=protos_dot_wallet__pb2.CreateWalletRequest.SerializeToString,
                response_deserializer=protos_dot_wallet__pb2.CreateWalletResponse.FromString,
                _registered_method=True)
        self.GetBalance = channel.unary_unary(
                '/wallet.WalletService/GetBalance',
                request_serializer=protos_dot_wallet__pb2.GetBalanceRequest.SerializeToString,
                response_deserializer=protos_dot_wallet__pb2.GetBalanceResponse.FromString,
                _registered_method=True)
        self.TransferFunds = channel.unary_unary(
                '/wallet.WalletService/TransferFunds',
                request_serializer=protos_dot_wallet__pb2.TransferFundsRequest.SerializeToString,
                response_deserializer=protos_dot_wallet__pb2.TransferFundsResponse.FromString,
                _registered_method=True)
        self.GetTransactionHistory = channel.unary_unary(
                '/wallet.WalletService/GetTransactionHistory',
                request_serializer=protos_dot_wallet__pb2.GetTransactionHistoryRequest.SerializeToString,
                response_deserializer=protos_dot_wallet__pb2.GetTransactionHistoryResponse.FromString,
                _registered_method=True)
        self.GetConversionHistory = channel.unary_unary(
                '/wallet.WalletService/GetConversionHistory',
                request_serializer=protos_dot_wallet__pb2.GetConversionHistoryRequest.SerializeToString,
                response_deserializer=protos_dot_wallet__pb2.GetConversionHistoryResponse.FromString,
                _registered_method=True)
        self.ListWallets = channel.unary_unary(
                '/wallet.WalletService/ListWallets',
                request_serializer=protos_dot_wallet__pb2.ListWalletsRequest.SerializeToString,
                response_deserializer=protos_dot_wallet__pb2.ListWalletsResponse.FromString,
                _registered_method=True)


class WalletServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateWallet(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBalance(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TransferFunds(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTransactionHistory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetConversionHistory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListWallets(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WalletServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateWallet': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateWallet,
                    request_deserializer=protos_dot_wallet__pb2.CreateWalletRequest.FromString,
                    response_serializer=protos_dot_wallet__pb2.CreateWalletResponse.SerializeToString,
            ),
            'GetBalance': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBalance,
                    request_deserializer=protos_dot_wallet__pb2.GetBalanceRequest.FromString,
                    response_serializer=protos_dot_wallet__pb2.GetBalanceResponse.SerializeToString,
            ),
            'TransferFunds': grpc.unary_unary_rpc_method_handler(
                    servicer.TransferFunds,
                    request_deserializer=protos_dot_wallet__pb2.TransferFundsRequest.FromString,
                    response_serializer=protos_dot_wallet__pb2.TransferFundsResponse.SerializeToString,
            ),
            'GetTransactionHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTransactionHistory,
                    request_deserializer=protos_dot_wallet__pb2.GetTransactionHistoryRequest.FromString,
                    response_serializer=protos_dot_wallet__pb2.GetTransactionHistoryResponse.SerializeToString,
            ),
            'GetConversionHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetConversionHistory,
                    request_deserializer=protos_dot_wallet__pb2.GetConversionHistoryRequest.FromString,
                    response_serializer=protos_dot_wallet__pb2.GetConversionHistoryResponse.SerializeToString,
            ),
            'ListWallets': grpc.unary_unary_rpc_method_handler(
                    servicer.ListWallets,
                    request_deserializer=protos_dot_wallet__pb2.ListWalletsRequest.FromString,
                    response_serializer=protos_dot_wallet__pb2.ListWalletsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'wallet.WalletService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('wallet.WalletService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WalletService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateWallet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/wallet.WalletService/CreateWallet',
            protos_dot_wallet__pb2.CreateWalletRequest.SerializeToString,
            protos_dot_wallet__pb2.CreateWalletResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBalance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/wallet.WalletService/GetBalance',
            protos_dot_wallet__pb2.GetBalanceRequest.SerializeToString,
            protos_dot_wallet__pb2.GetBalanceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TransferFunds(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/wallet.WalletService/TransferFunds',
            protos_dot_wallet__pb2.TransferFundsRequest.SerializeToString,
            protos_dot_wallet__pb2.TransferFundsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTransactionHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/wallet.WalletService/GetTransactionHistory',
            protos_dot_wallet__pb2.GetTransactionHistoryRequest.SerializeToString,
            protos_dot_wallet__pb2.GetTransactionHistoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetConversionHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/wallet.WalletService/GetConversionHistory',
            protos_dot_wallet__pb2.GetConversionHistoryRequest.SerializeToString,
            protos_dot_wallet__pb2.GetConversionHistoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListWallets(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/wallet.WalletService/ListWallets',
            protos_dot_wallet__pb2.ListWalletsRequest.SerializeToString,
            protos_dot_wallet__pb2.ListWalletsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
